### ISSUE TITLE
日程の決定

### ISSUE THREAD

**Issue by denari** [kosen10s/lt02docs#1]
https://chouseisan.com/schedule/List?h=1aca5fe0d88842b1bc3ad79e2ec4b987&utm_source=cp

9/12でFixしようとしたが高専DJ部と被る問題発生。

調整さんを元にある程度人数が多い日にFixしたい。

**Comment by puhitaku** [comment]
まず目下の候補は9月13日(日)で、12からほとんど動かないからたぶんこれが最有力だと思う。
次に有力なのは9月6日(日)。

**Comment by denari** [comment]
上記2候補、高専カンファもかぶってなくて、あと高専界隈のイベントって何があるかわからないけど、問題なさそうな気はしている。

**Comment by pndcat** [comment]
とりあえず高専カンファもDJ部も避けれたなら大丈夫かと思われる

**Comment by denari** [comment]
んー、会場に対する相談もあるし、目下問題なさそうなので、9/13でFIXしましょう。
