### ISSUE TITLE
README.mdの活用

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt02docs#13]
決まったことをREADMEに書いておくと、今後わかりやすいかも。

issueで議論が終わってcloseしてしまうと、後から探すのに苦労すると思うので、リポジトリTOP
のREADMEに書いてあると確認しやすいと思う

**Comment by denari** [comment]
@NKMR6194 いいね、そうしよう。

**Comment by denari** [comment]
@NKMR6194 ありがとう、運用方法を適当にきめて、ブランチ切ってコミットしてみた。Pull Requestを出すので一応診てもらうことは可能??

**Comment by ysakasin** [comment]
@denari READMEの内容良いと思います :+1:
