### ISSUE TITLE
場所の確保

### ISSUE THREAD

**Issue by denari** [kosen10s/lt02docs#2]
前回会場もある。

せっかくなら社会人各位の務めてるオフィスを一通り検討したい（願望）

会場によっては会場側の講演をしてもらう可能性があるから必要に応じて対応する

**Comment by pndcat** [comment]
もしかすると，安く借りれる場所(渋谷)があるので，そちらを確認してもよいか？

ちなみに，その方に前回みたいな感じで，紹介講演はしてもらうと思う

**Comment by denari** [comment]
@marin72-com LGTM!
確認してみてほしい。すごく助かる。

Slackに質問をあげてくれてたけど、実は弦本ビルにしたい理由は「安い」以外にない。より安ければそちらにしたい思いはある。

一応、前回は確か4000円/時で借りてたハズ。

紹介講演はオッケー。ただ、何分講演するかは相談させてほしい。
理想は15分以内だけど、30分までは仕方ないと思う。

**Comment by pndcat** [comment]
@DeNAri はい，承りました！

その方に紹介するようで，なんかいいスライドとかないですかね？
LT01はこんな感じでした！！！みたいな

**Comment by pndcat** [comment]
@DeNAri なければわたしがﾃｷﾄｰにほげほげっとします．
写真見せたりします．
記憶が怪しいのですが，OPトークか最後のまとめスライドとかでも何か資料があればください〜ぐらいです

**Comment by denari** [comment]
@marin72-com 現状無い〜。けども、そんな時間かからなそうだし、俺まとめるわ。明日までにできそうな気がしている。気だけ。

なっさまには他のissueも一通り目を通してほしいし。

**Comment by pndcat** [comment]
お願い済done

場所：HiveShibuya 
住所：東京都渋谷区道玄坂２丁目１０ 新大宗ビル３号館
