### ISSUE TITLE
公式「懇親会」？

### ISSUE THREAD

**Issue by denari** [kosen10s/lt02docs#9]
やるか否かもあると思うが、ここはぜひやりたい。

可能な範囲であらかじめ予約？
周辺の店を幾つかリストアップしておくとかでも当日動く時に役立ちそう

**Comment by unasuke** [comment]
任されました

**Comment by unasuke** [comment]
こんな感じだろうなという感じ(地図の中心が会場です)
<img width="1007" alt="__ _" src="https://cloud.githubusercontent.com/assets/4487291/9734578/1b30860e-566f-11e5-9a11-4e7228dc3acb.png">

**Comment by denari** [comment]
和食りん　渋谷店  しぶりん

**Comment by unasuke** [comment]
近めの店で、15人以上で入れそうな店を抜き出しました
- [鶏豚きっちん 渋谷道玄坂店 - 渋谷/焼鳥 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13112649/)
- [一献楽食 とら 渋谷道玄坂 - 神泉/居酒屋 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13140377/)
- [白木屋 渋谷道玄坂店 - 渋谷/居酒屋 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13051857/)
- [腹八分目 渋谷道玄坂店 - 渋谷/居酒屋 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13130057/)

**Comment by unasuke** [comment]
[一献楽食 とら 渋谷道玄坂 - 神泉/居酒屋 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13140377/)

9月13日 18時から 15人前後 中村 で予約しました。
